<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>OKET.Input</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OKET.Core\OKET.Core.csproj" />
  </ItemGroup>

</Project>
